run_name: resnet_50_epochs
p_type: photon
dtype: float32
# Data
hdf5_file: /data/projects/punim0011/aore/CaloChallenge/1/dataset_1_photons_1.hdf5
xml_filename: /data/projects/punim0011/aore/calo_dreamer/src/challenge_files/binning_dataset_1_photons.xml
width_noise: 5.0e-6
val_frac: 0.2
eps: 1.0e-10
particle_type: "photon"
eval_dataset: "1-photons"
transforms: {
  NormalizeByElayer: {ptype: /data/projects/punim0011/aore/calo_dreamer/src/challenge_files/binning_dataset_1_photons.xml, xml_file: photon},
  AddNoise: {noise_width: 5.0e-6},
  LogTransform: {alpha: 1.0e-6},
  Standardize: {means: -6.0, stds: 4.0}
}

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 256
validate_every: 100
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 0.01
betas: [0.9, 0.999]
n_epochs: 50
cycle_epochs: 50
save_interval: 100

# Sampling
sample_periodically: False
sample_every: 100
sample_every_n_samples: 100

network: Resnet
# network: SimpleUNet
# dim: 368
dim: 373

# ResNet block
intermediate_dim: 256
n_blocks: 1
n_con: 1
layers_per_block: 3
conditional: True

# U-Net
hidden_dims: [256, 128, 64]
condition_dim: 1
encode_t: True
encode_t_dim: 16
encode_c: True
encode_c_dim: 16

# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6