run_name: tbd_25k_epochs_logitu
dtype: float32

# Data
hdf5_file: /data/projects/punim0011/aore/CaloChallenge/1/dataset_1_photons_1.hdf5
eval_hdf5_file: /data/projects/punim0011/aore/CaloChallenge/1/dataset_1_photons_2.hdf5
xml_filename: /home/aore/calo_dreamer/src/challenge_files/binning_dataset_1_photons.xml
val_frac: 0.2
eps: 1.0e-10
particle_type: "photon"
eval_dataset: "1-photons"
transforms: {
    NormalizeByElayer: {
        ptype: /home/aore/calo_dreamer/src/challenge_files/binning_dataset_1_photons.xml,
        xml_file: photon
    },
    SelectiveUniformNoise: {noise_width: 5.0e-6, cut: True, exclusions: [-5, -4, -3, -2, -1]},
    SelectiveLogTransform: {
        alpha: 1.0e-6, exclusions: [-5, -4, -3, -2, -1], include_E: True
    },
    SelectiveLogitTransform: {
        delta: 1.0e-6, inclusions: [-4, -3, -2, -1]
    },
    StandardizeFromFile: {
        mean_path: /home/aore/calo_dreamer/dat/means_1_photons_1_logitu.npy,
        std_path: /home/aore/calo_dreamer/dat/stds_1_photons_1_logitu.npy,
        create: True
    },
    ScaleEnergy: {e_min: 5.545177, e_max: 15.249238},
}

# Training
lr: 1.e-3
max_lr: 5.e-4
batch_size: 4000
validate_every: 1
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 0.001
betas: [0.9, 0.999]
n_epochs: 25_000
cycle_epochs: 25_000
cycle_pct_start: 0.1
save_interval: 100_001

# Sampling
sample_periodically: False
sample_every: 4001
sample_every_n_samples: 1000

network: Resnet
shape: [373]

# ResNet block
intermediate_dim: 2000
n_blocks: 3
n_con: 1
layers_per_block: 2
conditional: True
encode_t: True
encode_t_dim: 100
encode_c: True
encode_c_dim: 100
normalization: LayerNorm