run_name: d2_ae
dtype: float32

# Model
model_type: energy

# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_1.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge//dataset_2_2.hdf5
xml_filename: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.2
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"

transforms: {
    NormalizeByElayer: {
        ptype: /remote/gpu02/aore/calo_dreamer/src/challenge_files/binning_dataset_2.xml,
        xml_file: electron
    },
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
}

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 128
validate_every: 10
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 0.0001
betas: [0.9, 0.999]
n_epochs: 200
cycle_epochs: 200
cycle_pct_start: 0.2
save_interval: 100_001

# Sampling
reconstruct: True
sample_periodically: False
batch_size_sample: 256

# Network
model: AE
network: AutoEncoder
condition_dim: 46

# AutoEncoder
ae_loss: 'bce'
ae_level_channels: [64, 4]
ae_level_kernels: [[3,4,3]]
ae_level_strides: [[3,2,1]]
ae_level_pads: [[0,0,0]]
ae_break_dims: [2,4]
ae_encode_c: True
ae_encode_c_dim: 100
