run_name: d2_test_ae
dtype: float32

# Model
model_type: shape
energy_model: /remote/gpu06/favaro/CaloDream/calo_dreamer/results/20240103_191958_d3_energy_model/

# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_1.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_2.hdf5
xml_filename: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.01
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"
eval_cut: 15.15e-3
shape: [45, 16, 9]

transforms: {
    NormalizeByElayer: {
      ptype: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml,
      xml_file: electron
    },
    # ZeroMask: {cut: 1.e-4},
    #Reweight: {factor: 0.9},
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
    AddFeaturesToCond: {split_index: 6480},
    Reshape: {shape: [45, 16, 9]}
}

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 500
validate_every: 10
use_scheduler: True
lr_scheduler: CosineAnnealing
# weight_decay: 0.0001
betas: [0.9, 0.999]
n_epochs: 500
cycle_epochs: 500
cycle_pct_start: 0.2
save_interval: 100_001

# Sampling
reconstruct: True
sample_periodically: False
sample_every: 10
batch_size_sample: 256
sample_every_n_samples: 1001

# Network
model: AE
network: AutoEncoder
condition_dim: 46

# AutoEncoder
ae_loss: 'bce'
ae_level_channels: [64, 4]
ae_level_kernels: [[4,3]]
ae_level_strides: [[2,1]]
ae_level_pads: [[0]]
ae_encode_c: True
ae_encode_c_dim: 100
ae_break_dims: [3]
