run_name: BespokeMidpoint_1_largebatch
dtype: float32

# Data
shape: [1, 45, 16, 9]

# Solver
model: BespokeMidpoint
num_steps: 1 # number of integration steps (NFE varies with base solver)
truth_tols: # setting for the dopri5 'truth' solver
  atol: 1.e-5
  rtol: 1.e-5

# Flow model
shape_model: /home/aore/calo_dreamer/results/d2_submit_shape

# Training
loss: gte
iterations: 5000
batch_size: 1000
lr: 1.e-3
loss_window: 250

# Evaluation
batch_size_sample: 100
n_batches_sample: 25
eval_mode: hist-chi
