run_name: d2_bespoke
dtype: float32

# Data
shape: [1, 45, 16, 9]

# Solver
model: BespokeMidpoint
num_steps: 2 # number of integration steps (NFE varies with base solver)
truth_tols: # setting for the dopri5 'truth' solver
  atol: 1.e-5
  rtol: 1.e-5

# Flow model
shape_model: /home/aore/calo_dreamer/results/20240110_124434_d2_2000_epoch_shape_model_geom

# Training
iterations: 600
batch_size: 5
lr: 1.e-3
betas: [0.9, 0.999]

# Sampling
# batch_size_sample: 500
# n_batches_sample: 2
