run_name: BespokeMidpoint_4_dopri1e3
dtype: float32

# Data
shape: [1, 45, 16, 9]

# Solver
model: BespokeMidpoint
num_steps: 32 # number of integration steps (NFE varies with base solver)
truth_tols: # setting for the dopri5 'truth' solver
  atol: 1.e-4
  rtol: 1.e-4

# Flow model
shape_model: /home/aore/calo_dreamer/results/20240207_025523_d2_2000_epoch_shape_model_geom

# Training
loss: gte
iterations: 5000
batch_size: 40
lr: 1.e-3
loss_window: 250

# Evaluation
batch_size_sample: 100
n_batches_sample: 25
eval_mode: hist-chi
