run_name: d2_latent_test
dtype: float32

# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_1.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_2.hdf5
xml_filename: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.2
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"
eval_cut: 15.15e-3
shape: [4, 15, 7, 7] # shape of the autoencoder embedding

# Model
model: "TransfusionAR"
network: ARtransformer_shape
n_con: 46
dim_embedding: 256
n_head: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 512
encode_t_dim: 64

# Secondary models
energy_model: /remote/gpu02/ore/calo_dreamer/results/20240222_201728_d2_energy_model_ARtransformer_LTF
autoencoder: /remote/gpu02/ore/calo_dreamer/results/20240222_231711_d2_test_ae

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 1000
validate_every: 5
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 0.0001
betas: [0.9, 0.999]
n_epochs: 500
cycle_epochs: 500
cycle_pct_start: 0.1
save_interval: 100_001

# Sampling
sample_periodically: False
sample_every: 10
sample_every_n_samples: 1001
solver_kwargs: {method: midpoint, options: {step_size: 0.02}}