run_name: d2_vit_1k
dtype: float32

# Model
model_type: shape
energy_model: /remote/gpu02/ore/calo_dreamer/results/20240213_104847_d2_energy_model_ARtransformer
# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_1.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_2.hdf5
xml_filename: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.2
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"
eval_cut: 15.15e-3
shape: [1, 45, 16, 9]

transforms: {
    NormalizeByElayer: {
        ptype: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_2.xml,
        xml_file: electron
    },
    SelectiveUniformNoise: {
        noise_width: 5.0e-6,
        cut: True,
        exclusions: [-45, -44, -43, -42, -41, -40, -39, -38, -37,
                     -36, -35, -34, -33, -32, -31, -30, -29, -28,
                     -27, -26, -25, -24, -23, -22, -21, -20, -19,
                     -18, -17, -16, -15, -14, -13, -12, -11, -10,
                      -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1]
    },
    ExclusiveLogitTransform: {delta: 1.0e-6, exclusions: [-45]},
    StandardizeFromFile: {},
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
    AddFeaturesToCond: {split_index: 6480},
    Reshape: {shape: [1, 45, 16, 9]}
}

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 250
validate_every: 5
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 1.e-3
betas: [0.9, 0.999]
n_epochs: 1000
cycle_epochs: 1000
cycle_pct_start: 0.1
save_interval: 100_001

# Sampling
sample_periodically: False
sample_every: 10
sample_every_n_samples: 1001
solver_kwargs: {method: rk4, options: {step_size: 0.02}}

# Network
network: ViT
condition_dim: 46
patch_shape: [5, 4, 3]
hidden_dim: 480
depth: 4
num_heads: 8
mlp_ratio: 4.0

# patch_shape: [3, 2, 1]
# hidden_dim: 480
# depth: 8
# num_heads: 8
# mlp_ratio: 4.0