run_name: d3_ae
dtype: float32

# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_3_1_full.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_3_2_full.hdf5
xml_filename: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_3.xml
val_frac: 0.05
eps: 1.0e-10
particle_type: electron
eval_dataset: "3"
eval_cut: 15.15e-3
shape: [45, 50, 18]

transforms: {
    NormalizeByElayer: {
      ptype: /remote/gpu02/ore/calo_dreamer/src/challenge_files/binning_dataset_3.xml,
      xml_file: electron
    },
    ZeroMask: {cut: 1.e-4},
    #Reweight: {factor: 0.9},
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
    AddFeaturesToCond: {split_index: 40500},
    Reshape: {shape: [45, 50, 18]}
}

# Training
lr: 5.e-4
# max_lr: 1.e-3
batch_size: 250
validate_every: 10
use_scheduler: True
lr_scheduler: CosineAnnealing
# weight_decay: 0.0001
betas: [0.9, 0.999]
n_epochs: 500
cycle_epochs: 500
cycle_pct_start: 0.2
save_interval: 100_001

# Sampling
reconstruct: True
sample_periodically: False
sample_every: 10
batch_size_sample: 2000
sample_every_n_samples: 1001

# Model
model_type: shape
model: AE
network: AutoEncoder
condition_dim: 46

# AutoEncoder
ae_loss: bce_kl
ae_kl: True
ae_kl_beta: 1.e-6
ae_level_channels: [64, 64, 3]  # (1,50,18) -> (3, 16, 8)
ae_level_kernels: [[5,4], 1]    #       900 -> 382
ae_level_strides: [[3,2], 1]    #    = x2.35 reduction
ae_level_pads: [0, 0]

ae_encode_c: True
ae_encode_c_dim: 100
ae_break_dims: [3]
