run_name: dset_2_test
dtype: float32

# Data
hdf5_file: /data/projects/punim0011/aore/CaloChallenge/2/dataset_2_1.hdf5
eval_hdf5_file: /data/projects/punim0011/aore/CaloChallenge/2/dataset_2_2.hdf5
xml_filename: /home/aore/calo_dreamer/src/challenge_files/binning_dataset_2.xml
val_frac: 0.2
eps: 1.0e-10
particle_type: "electron"
eval_dataset: "2"
shape: [1, 45, 16, 9]
transforms: {
  NormalizeByEinc: {},
  AddNoise: {noise_width: 5.e-7, cut: True},
  LogTransform: {alpha: 1.0e-6},
  StandardizeFromFile: {
      mean: /home/aore/calo_dreamer/dat/means_2_1.npy,
      std: /home/aore/calo_dreamer/dat/stds_2_1.npy
  },
  Reshape: {shape: [1, 45, 16, 9]}
}

# Training
lr: 1.e-4
max_lr: 1.e-3
batch_size: 2048
validate_every: 1
use_scheduler: True
lr_scheduler: one_cycle_lr
weight_decay: 0.001
betas: [0.9, 0.999]
n_epochs: 100
cycle_epochs: 100
save_interval: 1001

# Sampling
sample_periodically: False
sample_every: 10
sample_every_n_samples: 1001

# Network
network: UNet
condition_dim': 1
level_channels': [16, 64, 128]
encode_t': True
encode_t_dim': 32
encode_c': True
encode_c_dim': 32
